### ISSUE TITLE
How to set base url?

### ISSUE THREAD

**Issue by PaulinaPacyna** [qdrant/qdrant-helm#120]
Hi, 
I am using the https://github.com/qdrant/qdrant-helm chart to deploy the qdrant application on kubernetes cluster. The dasjboard is correctly displayed under localhost:6333/dashboard, using port-forwarding to the pod created by statefulset. I would like to expose the application under a url with a [VirtualService](https://istio.io/latest/docs/reference/config/networking/virtual-service/). However, the app cannot be hosted at `/` path (it is reserved), so I am mapping the requests coming from `/ABC/DEF/` to `/`. 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: qdrant
spec:
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: "/ABC/DEF/"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: qdrant.db.svc.cluster.local
        port:
           number: 6333

```
The app seems to be partly visible. `/ABC/DEF` displays version info (`{"title":"qdrant - vector search engine", "version":"1.7.2"}`
However `/ABC/DEF/dashboard` loads a blank page, with an icon and "Qdrant Web UI" in the tab title. As far as I managed to debug this issue, the app tries to query the `/dashboard`, `/telemetry` and `/collections` endpoints to load the data and fails. Is there a possibility to set the base url in the application, so the app knows that it must refer to `/ABC/DEF/dashboard`, `/ABC/DEF/telemetry` and `/ABC/DEF/collections`? 
Thanks you in advance.
