### ISSUE TITLE
Missing condition for binding snapshot volume

### ISSUE THREAD

**Issue by kyue1005** [qdrant/qdrant-helm#20]
https://github.com/qdrant/qdrant-helm/blob/main/templates/statefulset.yaml#L107

```yaml
- name: qdrant-snapshots
          persistentVolumeClaim:
            claimName: {{ .Values.snapshotRestoration.pvcName }}
```

the block above should be added only when `.Values.snapshotRestoration.enabled` is true
