### ISSUE TITLE
ServiceMonitor's label selector matches both Service objects 

### ISSUE THREAD

**Issue by vitali-ipquants** [qdrant/qdrant-helm#218]
Hello Qdrant team,

The ServiceMonitor object created by the Helm chart uses a label selector matching the two service objects - the load balancer service and the headless service. 
As result in Prometheus there are duplicated targets.
In a cluster with 3 replicas, in Prometheus there are 6 targets - 3 per service.

This is observed in version 0.10.1 of the helm chart.

Thank you

**Comment by arthurk** [comment]
Hi,

the headless service has one extra label (`app.kubernetes.io/component`) which the other service doens't have. It shouldn't match both Services.

Headless Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-qdrant-headless
  labels:
    helm.sh/chart: qdrant-1.11.0
    app: qdrant
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.11.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: cluster-discovery
```

Other Service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-qdrant
  labels:
    helm.sh/chart: qdrant-1.11.0
    app: qdrant
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.11.0"
    app.kubernetes.io/managed-by: Helm
```

The ServiceMonitor:

```yaml
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
# ...
  selector:
    matchLabels:
      helm.sh/chart: qdrant-1.11.0
      app: qdrant
      app.kubernetes.io/name: qdrant
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/version: "v1.11.0"
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/component: cluster-discovery
```

Could you please double check that this is also the case in your config?
