### ISSUE TITLE
Can we use Qdrant cluster deployments persistent storage using NFS or S3 as backend ? 

### ISSUE THREAD

**Issue by agandra30** [qdrant/qdrant-helm#237]
Hello team,

We are trying to explore the options of using Qdrant using a NFS or S3 as storage backend completely .

We know as per the documentation, both NFS based mount paths or S3 endpoints wont work .

https://qdrant.tech/documentation/guides/installation/?q=storage#storage 

Curious to know if i provide the NFS share path in the configuration file , what would be the behaviour :

```
storage:
  # Where to store all the data
  storage_path: /nfs/qdrant/qdata

  # Where to store snapshots
  snapshots_path: /nfs/qdrant/qdata_snapshots
```
