### ISSUE TITLE
ArgoCD doesn't support helm k8s lookup and thus qdrant existing secret lookup fails

### ISSUE THREAD

**Issue by pschwager** [qdrant/qdrant-helm#249]
I just tried your latest changes with a ArgoCD deployment, by specifing a apiKeys via an existing secret like

```
apiKey:
  valueFrom:
     secretKeyRef:
       name: "secretname"
       key: "apikeyname"
```

This doesn't work, as ArgoCD doesn't support the helm lookup function:
https://github.com/argoproj/argo-cd/issues/5202

During debugging the issue I found out, that the qdrant helm chart tries to read the existing k8s secret and creates a new secret.

I'm looking for some alternative solution to specify the api keys outside the qdrant helm chart, so that I don't have to put the secerts as cleartext into our deployment repos... any suggestion?

**Comment by justbert** [comment]
Also hitting this. I think, instead of having the the template lookup the secret and copy it to a new secret, the secret could just be mounted. It needs to reside in the same namespace anyway.

**Comment by joseprsm** [comment]
Also facing this issue. I still haven't tested it but my current workaround is to pass these values to the environment variables of the StatefulSet.
```
  env:
    - name: QDRANT__SERVICE__API_KEY
      valueFrom:
        secretKeyRef:
          name: "secretname"
          key: "apikeyname"
```
