### ISSUE TITLE
Pod Fails with chown: changing ownership of '/qdrant/storage': Operation not permitted

### ISSUE THREAD

**Issue by rsrivastava-tw** [qdrant/qdrant-helm#303]
When deploying Qdrant with the provided Helm chart configuration, the pod fails to start due to a permission issue when attempting to change ownership of /qdrant/storage. The error observed is:
`chown: changing ownership of '/qdrant/storage': Operation not permitted
`

This happens despite running with appropriate permissions and ensuring that persistent storage is correctly mounted.

**Helm Values Override**
The following values were used in the deployment:
```
replicaCount: 3

config:
  cluster:
    enabled: true
  storage:
    optimizers:
      deleted_threshold: 0.5
      vacuum_min_vector_number: 1500
      default_segment_number: 2
      max_segment_size_kb: null
      memmap_threshold_kb: null
      indexing_threshold_kb: 25000
      flush_interval_sec: 5
      max_optimization_threads: 1

livenessProbe:
  enabled: true
  initialDelaySeconds: 60

resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 4Gi

tolerations:
  - key: "app.stateful/component"
    operator: "Equal"
    value: "qdrant"
    effect: NoSchedule

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: "app.stateful/component"
          operator: In
          values:
          - "qdrant"

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: qdrant
        app.kubernetes.io/instance: qdrant

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

persistence:
  accessModes: ["ReadWriteOnce"]
  size: 10Gi

apiKey: true

sidecarContainers:
  - name: metrics
    image: nginx:1.26
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    env:
    - name: QDRANT_APIKEY
      valueFrom:
        secretKeyRef:
          name: quadrant-qdrant-apikey
          key: api-key
```
