### ISSUE TITLE
Add appProtocol support

### ISSUE THREAD

**Issue by the-mousaillon** [qdrant/qdrant-helm#304]
**Request:**

Currently qdrant hem chart does not seem to support the appProtocol specification for the service.
Why ? Because it's the only way i got gRPC to work on gke, by setting the appProtocol of the grpc port to HTTP2

**Solution i'd like**

I would like to specify the appProtocol in the values.yaml

Example:
```yaml
service:
  type: ClusterIP
  additionalLabels: {}
  annotations: {}
  loadBalancerIP: ""
  ports:
    - name: http
      port: 6333
      targetPort: 6333
      protocol: TCP
      appProtocol: HTTPS
      checksEnabled: true

    - name: grpc
      port: 6334
      targetPort: 6334
      protocol: TCP
      appProtocol: HTTP2
      checksEnabled: false

    - name: p2p
      port: 6335
      targetPort: 6335
      protocol: TCP
      checksEnabled: false
```

It should be quite simple to add
ex: for the service-headless:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qdrant.fullname" . }}-headless
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster-discovery
{{- with .Values.service.additionalLabels }}
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      {{- if .appProtocol }}
      appProtocol: {{ .appProtocol }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "qdrant.selectorLabels" . | nindent 4 }}
```
