### ISSUE TITLE
Memory limit config not working

### ISSUE THREAD

**Issue by Barney241** [qdrant/qdrant-helm#31]
Hi i am deploying qdrant using argo. And i want to limit the memory usage of qdrant. I have this config

```
qdrant:
  persistence:
    size: 10Gi

  config:
    storage:
      optimizers:
        # Maximum size (in KiloBytes) of vectors to store in-memory per segment.
        # Segments larger than this threshold will be stored as read-only memmaped file.
        # To enable memmap storage, lower the threshold
        # Note: 1Kb = 1 vector of size 256
        # If not set, mmap will not be used.
        memmap_threshold_kb: 100000

        # Maximum size (in KiloBytes) of vectors allowed for plain index.
        # Default value based on https://github.com/google-research/google-research/blob/master/scann/docs/algorithms.md
        # Note: 1Kb = 1 vector of size 256
        indexing_threshold_kb: 23000

      # Default parameters of HNSW Index. Could be overridden for each collection individually
      hnsw_index:
        # Minimal size (in KiloBytes) of vectors for additional payload-based indexing.
        # If payload chunk is smaller than `full_scan_threshold_kb` additional indexing won't be used -
        # in this case full-scan search should be preferred by query planner and additional indexing is not required.
        # Note: 1Kb = 1 vector of size 256
        full_scan_threshold_kb: 50000
        # Store HNSW index on disk. If set to false, index will be stored in RAM. Default: false
        on_disk: false

  updateConfigurationOnChange: true

  resources:
    limits:
      cpu: 1500m
      memory: 3000Mi
    requests:
      cpu: 1000m
      memory: 2500Mi
```

I can see that this values are used because pvc has 10Gi, but pod is still beikng killed by k8 because of the memory limit.
I have already indexed something about 1M points not shure exactly. But the qdrant pod is in crash loop and it doesnt seem like changing `memmap_threshold_kb` helps.

When i described the productin.yml i got this
```
production.yaml:
----
cluster:
  consensus:
    tick_period_ms: 100
  enabled: true
  p2p:
    port: 6335
storage:
  hnsw_index:
    full_scan_threshold_kb: 50000
    on_disk: false
  optimizers:
    indexing_threshold_kb: 23000
    memmap_threshold_kb: 100000
```
