### ISSUE TITLE
Might want to add an ingress to the chart

### ISSUE THREAD

**Issue by trashhalo** [qdrant/qdrant-helm#32]
It looks like a couple people (including myself) had to fork this chart to add an ingress. This is ours, but it could be a common need.

```yaml
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qdrant-ingress
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "qdrant.fullname" . }}
                port:
                  number: 6333
{{- end -}}
```

**Comment by fabriziobonavita** [comment]
Thank you for bringing this up @trashhalo, we had some question about a generic ingress already, we'll add that!

**Comment by gulldan** [comment]
how you cut ports ?
qdrant always add port and check dns with port.

for qrpc ive tried 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "qdrant.fullname" . }}-grpc
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/grpc-backend: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  rules:
  - host: qdrant.test
    http:
      paths:
      - backend:
          service:
            name: {{ include "qdrant.fullname" . }}
            port:
              number: 6334
        path: /grpc/([^:6334]+)
        pathType: Prefix
```

but have an err in python client

```
from qdrant_client import QdrantClient
client = QdrantClient(host="qdrant.test/grpc", prefer_grpc=True)
client.get_collections()

```


```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "DNS resolution failed for qdrant.test/grpc:6334: C-ares status is not ARES_SUCCESS qtype=AAAA name=qdrant.test/grpc/ is_balancer=0: Domain name not found"
debug_error_string = "UNKNOWN:DNS resolution failed for qdrant.test/grpc:6334: C-ares status is not ARES_SUCCESS qtype=AAAA name=qdrant.test/grpc is_balancer=0: Domain name not found {grpc_status:14, created_time:"2023-06-19T12:31:29.575711879+03:00"}"
>
```

same problem with http, above example doesnt work
