### ISSUE TITLE
Generating apiKey

### ISSUE THREAD

**Issue by apocalypsation1** [qdrant/qdrant-helm#346]
Followed your values.yaml chart regarding on apiKey. 
I want to create my own api key instead of qdrant generating it. 
But when i run together with the helm installl. qdrant will generate one `qdrant-vector-apikey` and my test-qdrant in secret. 
And the statefulset will be using `qdrant-vector-apikey` instead of test-qdrant.

```
apiKey:
  valueFrom:
    secretKeyRef:
      name: test-qdrant
      key: qdrant-key
```
Problem with the use of lookup() function in the helm chart's helpers.tpl file, i don't have a running kubernetes cluster to query the secret from. 

`{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (printf "%s-apikey" (include "qdrant.fullname" . ))) | default dict -}}`
