### ISSUE TITLE
Support disabling qdrant from Values file

### ISSUE THREAD

**Issue by andreped** [qdrant/qdrant-helm#350]
In one of our production applications, we want to do two different deployments, where we are able to enable/disable Qdrant from a Values.yml or Argo file.

From looking through the code, I fail to see that you support a global `enabled` flag. I have seen that in other helm charts provided by different vendors and solution.

I can draft a PR to this, if this would be of interest. If not, I would be interested to know why :]

**Comment by andreped** [comment]
It is possible to do something like this:

```
# Your chart/Chart.yaml
...
dependencies:
  - name: qdrant
    repository: https://qdrant.github.io/qdrant-helm
    version: 1.14.1
    condition: qdrant.enabled    # <<<==== THIS DOES THE MAGIC


# Your chart/values.yaml
...
qdrant:
  enabled: true
```

More info can be found at:
https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags
