### ISSUE TITLE
For Qdrant to work nicely with Istio the services should define appProtocol

### ISSUE THREAD

**Issue by wodka** [qdrant/qdrant-helm#43]
It would be great if qdrant would define the appProtocol to work nicely with istio https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol

```
service:
  type: ClusterIP
  annotations: {}
  ports:
    - name: rest
      port: 6333
      targetPort: 6333
      protocol: TCP
      appProtocol: http
      checksEnabled: true
    - name: grpc
      port: 6334
      targetPort: 6334
      protocol: TCP
      appProtocol: grpc
      checksEnabled: false
    - name: p2p
      port: 6335
      targetPort: 6335
      protocol: TCP
      appProtocol: tcp
      checksEnabled: false
```

and with this to also add it in the service definition

```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qdrant.fullname" . }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      appProtocol: {{ .appProtocol | default "http" }}
    {{- end }}
  selector:
    {{- include "qdrant.selectorLabels" . | nindent 4 }}
```
