### ISSUE TITLE
add support for statefulset labels 

### ISSUE THREAD

**Issue by thetkoseek** [qdrant/qdrant-helm#55]
Unified service tagging in datadog requires us to label deployments / statefulsets.

Ie:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tags.datadoghq.com/env: "<ENV>"
    tags.datadoghq.com/service: "<SERVICE>"
    tags.datadoghq.com/version: "<VERSION>"
...
template:
  metadata:
    labels:
      tags.datadoghq.com/env: "<ENV>"
      tags.datadoghq.com/service: "<SERVICE>"
      tags.datadoghq.com/version: "<VERSION>"
```

currently adding labels to pods is supported through podLabels, but is lacking support to label statefulsets
