### ISSUE TITLE
Passing the API Key from vault to the helm chart

### ISSUE THREAD

**Issue by zimmerling** [qdrant/qdrant-helm#83]
I want to pass the API key stored in vault to the helm chart. If I see it correctly, there is no possibility for this yet.

One solution might be to add an `existingConfigurationSecret` key set to the name of the Kubernetes secret that contains the configuration.

In the values.yaml of the helm chart, we would then define `existingConfigurationSecret: my-config` and mount that secret into the container.

I could then provision and populate the secret with a secret from vault with my secrets-operator. I would save the config (containing sensitive data) to vault, and the secrets-operator syncs it into a Kubernetes secret.

**Comment by bashofmann** [comment]
I think this is already possible.

You can configure and `additionalVolumes` from your existing secret:

```
additionalVolumes:
  - name: custom-config-secret
     secret:
       secretName: existing-secret-name
       defaultMode: 0600
```

The secret should have a key `local.yaml` with your api key configuration (https://qdrant.tech/documentation/guides/security/):

```
service:
  api_key: your-api-key
```

And then mount this volume into the Qdrant Pods:

```
additionalVolumeMounts:
  - name: custom-config-secret
     mountPath: /qdrant/config/local.yaml
     subPath: local.yaml
```
